<h1>Descriptive
</h1>

In [2]:
#Mean
import numpy as np
data = [1, 2, 3, 4, 5]
print(np.mean(data))  # Output: 3.0


3.0


In [3]:
#Median
print(np.median(data))  # Output: 3.0


3.0


<img src ='Median.png'>


In [4]:
#Variance
print(np.var(data))  # Output: 2.0


2.0


<h3>The variance is a measure of the spread or dispersion of a dataset. It quantifies how far each data point is from the mean. A higher variance indicates that the data points are more spread out from the mean, while a lower variance indicates that they are closer to the mean.</h3>

<img src='var1.png'>
<img src='var2.png'>

In [5]:
#std 

print(np.std(data))  # Output: 1.4142135623730951


1.4142135623730951


<h3>The standard deviation is a measure of the spread or dispersion of a dataset. It is the square root of the variance, 
</h3>

In [6]:
print(np.sum(data))  # Output: 15


15


In [7]:
print(np.prod(data))  # Output: 120


120


In [8]:
#Percentiles and Quantiles
#Percentiles
print(np.percentile(data, 50))  # Output: 3.0 (Median)


3.0


<h3>Percentiles
A percentile is a measure that indicates the value below which a given percentage of data points in a dataset falls. For example, the 50th percentile (median) is the value below which 50% of the data lies.</h3>

<img src='percentile.png'>
<img src='percentile1.png'>

In [9]:
print(np.min(data))  # Output: 1
print(np.max(data))  # Output: 5

1
5


In [11]:
#Range
print(np.ptp(data))  # Output: 4 (5 - 1)


4


<h1>Cumulative Statistics</h1>

In [14]:
#Cumulative Sum


data = [1, 2, 3, 4, 5]
print(np.cumsum(data))  # Output: [ 1  3  6 10 15]


[ 1  3  6 10 15]


In [15]:
#Cumulative Product
print(np.cumprod(data))  # Output: [  1   2   6  24 120]


[  1   2   6  24 120]


<h3>Correlations and Covariance</h3>

In [16]:
#Correlation Coefficient
x = [1, 2, 3]
y = [4, 5, 6]
print(np.corrcoef(x, y))  # Output: [[1. 1.]
                             #          [1. 1.]]


[[1. 1.]
 [1. 1.]]


In [17]:
#Covariance Matrix
print(np.cov(x, y))  # Output: [[1. 1.]
                            #          [1. 1.]]

[[1. 1.]
 [1. 1.]]


The correlation coefficient quantifies the linear relationship between two variables. It measures how changes in one variable are associated with changes in another. Its value ranges from -1 to 1




1: Perfect positive correlation (as one variable increases, the other increases).

−1: Perfect negative correlation (as one variable increases, the other decreases).

0: No linear correlation.



<img src='corr.png'>

In [18]:
X=[1,2,3,4,5]
Y=[2,4,6,8,10]


<h3>Statistical Distributions</h3>

In [19]:
#Normal Distribution
normal_sample = np.random.normal(loc=0, scale=1, size=5)
print(normal_sample)  # Example Output: [ 1.764, -0.977, 0.950, -0.151, 0.410]


[-0.55864821  0.55616421  1.22705683 -0.70914754  0.54041146]


Normal Distribution
The normal distribution, also known as the Gaussian distribution, is a continuous probability distribution that is symmetric around its mean. It is one of the most important and widely used distributions in statistics and data analysis.

In [20]:
#Uniform Distribution
uniform_sample = np.random.uniform(low=0, high=10, size=5)
print(uniform_sample)  # Example Output: [5.23, 3.57, 7.68, 0.91, 8.42]


[5.75869955 2.41276841 5.56415143 5.8220786  5.39359617]


The uniform distribution is a probability distribution where all outcomes are equally likely. Every interval of the same length within the range of the distribution has an equal probability of occurring.

In [21]:
#Binomial Distribution
binomial_sample = np.random.binomial(n=10, p=0.5, size=5)
print(binomial_sample)  # Example Output: [4, 6, 5, 7, 3]


[7 5 2 5 6]


In [25]:
import numpy as np

# Define the array
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Create the histogram
hist, bins = np.histogram(array, bins=3)

# Output the histogram and bin edges
print("Histogram:", hist)  # Counts of elements in each bin
print("Bins:", bins)  # Bin edges


Histogram: [1 2 7]
Bins: [1. 2. 3. 4.]


<img src='bin1.png'>

In [26]:
import numpy as np

# Define the array
array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4])

# Create the histogram with 3 bins
hist, bins = np.histogram(array, bins=3)

print("Histogram:", hist)  # Counts of elements in each bin
print("Bins:", bins)  # Bin edges


Histogram: [1 2 7]
Bins: [1. 2. 3. 4.]


<img src='bin2.png'>

In [27]:
# Define custom bin edges
custom_bins = [0, 2, 3, 5]

# Create the histogram using custom bins
hist, bins = np.histogram(array, bins=custom_bins)

print("Histogram:", hist)  # Counts of elements in each bin
print("Bins:", bins)  # Bin edges


Histogram: [1 2 7]
Bins: [0 2 3 5]
