<h1>What is NumPy?</h1>
NumPy (Numerical Python) is a library in Python used for numerical and matrix computations.

<h3>Installation</h3>

In [1]:
!pip install numpy



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


<h3>Import NumPy</h3>

In [2]:
import numpy as np


<h3>What is an Array?</h3>

An array is a data structure that stores multiple values of the same data type in a single variable. Arrays are like lists in Python, but they are more efficient for numerical operations and can handle multi-dimensional data.

In the context of NumPy, an array is called a NumPy array, which is essentially:


-A grid of values, all of the same type.

-Organized into dimensions (1D, 2D, 3D, or more).

-Fast and memory-efficient for numerical computations

<h3>Key Features of Arrays</h3>

-Homogeneous: All elements in a NumPy array must be of the same type (e.g., integers, floats).

-Fixed Size: Once created, the size of a NumPy array cannot be changed (unlike Python lists).

-Multi-dimensional: NumPy arrays support more than one dimension (1D, 2D, or nD).

-Efficient Computation: NumPy uses optimized C libraries, making array operations much faster than Python lists.

-Mathematical Operations: Arrays support vectorized operations, enabling element-wise addition, multiplication, etc., without explicit loops.

<img src='array.jpg'>

<h3>Why Use Arrays Instead of Lists?</h3>

<img src ='diffbtweenNumpyList.png'>

<h3>How is a NumPy Array Different?</h3>

Consider this example:


In [3]:
#Using Python Lists
list1 = [1, 2, 3]
list2 = [4, 5, 6]

# Element-wise addition requires a loop
result = [list1[i] + list2[i] for i in range(len(list1))]
print(result)  # Output: [5, 7, 9]


[5, 7, 9]


In [4]:
#Using NumPy Arrays
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition is automatic
result = arr1 + arr2
print(result)  # Output: [5, 7, 9]


[5 7 9]


In [5]:
list1+list2

[1, 2, 3, 4, 5, 6]

With NumPy arrays, operations like addition, subtraction, and multiplication are element-wise and efficient.

<h3>
Creating Arrays
</h3>

In [7]:
# 1D array
arr1 = np.array([1, 2, 3])
print(arr1)


[1 2 3]


In [8]:
# 2D array
arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [9]:
# 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


<h3>Array Attributes</h3>

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [11]:
print("Shape:", arr.shape)   

Shape: (2, 3)


In [12]:
print("Size:", arr.size) 

Size: 6


In [13]:
print("Data type:", arr.dtype)

Data type: int32


<h3>Array Initialization</h3>

In [3]:
# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# Random array
random_arr = np.random.rand(2, 3)  # Uniformly distributed
print(random_arr)

[[0.37012518 0.66349845 0.49815365]
 [0.48741894 0.83787523 0.07321934]]


In [5]:
random_arr = np.random.rand(2,2,3)  # Uniformly distributed
print(random_arr)

[[[0.18671546 0.1632629  0.28950272]
  [0.51863919 0.32103079 0.41613097]]

 [[0.45515326 0.62992676 0.01930696]
  [0.56552704 0.98593991 0.48974827]]]


Breaking It Down

np.random.rand Function:

This is a function from NumPy's random module.

It generates random numbers uniformly distributed in the range [0, 1), meaning:

Any number in this range is equally likely to appear.

No bias toward any part of the range.

Arguments (2, 3):

These specify the shape of the output array.

(2, 3) means:2 rows and 3 columns.

The output will be a 2-dimensional array.
Output:

A 2x3 array with random values between 0 (inclusive) and 1 (exclusive).

In [8]:
# Array of ones
ones = np.ones((3, 4,5))
print(ones)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [9]:
# Identity matrix
identity = np.eye(4)
print(identity)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
# Array with a range of values
range_arr = np.arange(0, 10, 2)
print(range_arr)


[0 2 4 6 8]


<h3>Indexing and Slicing</h3>

In [11]:
arr = np.array([10, 20, 30, 40, 50])

In [13]:
arr[-2]

40

In [14]:
arr[1:4]

array([20, 30, 40])

In [26]:
arr.shape

(5,)

In [24]:
# Indexing
print(arr[1])  # 20

20


In [21]:
# Slicing
print(arr[1:4])  # [20, 30, 40]


[20 30 40]


In [16]:
# Multi-dimensional slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[1:, 1:])  # [[5, 6], [8, 9]]


[[5 6]
 [8 9]]


In [18]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d[0:2,1:-1]

array([[2],
       [5]])

In [17]:
arr2d.shape

(3, 3)

In [25]:
arr2d.shape

(3, 3)

<h3>Mathematical Operations</h3>

In [27]:
# Element-wise operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [28]:
print(a + b)  # [5, 7, 9]

[5 7 9]


In [29]:
print(a * b)  # [4, 10, 18]

[ 4 10 18]


In [25]:
# Broadcasting
c = np.array([[1, 2], [3, 4]])

In [26]:
print(c + 10)  # Adds 10 to every element


[[11 12]
 [13 14]]


In [27]:
c-10

array([[-9, -8],
       [-7, -6]])

In [33]:
# Aggregations
arr = np.array([1, 2, 3, 4])

In [34]:
print(np.sum(arr))       # 10

10


In [35]:
print(np.mean(arr))      # 2.5

2.5


In [36]:
print(np.max(arr))       # 4

4


In [37]:
print(np.min(arr))  

1


<h3>Linear Algebra</h3>

In [31]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [32]:
A

array([[1, 2],
       [3, 4]])

In [39]:
# Matrix multiplication
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


<img src='matrix_dot.png'>

In [40]:
# Determinant
print(np.linalg.det(A))

-2.0000000000000004


In [28]:
np.det(A)

AttributeError: module 'numpy' has no attribute 'det'

<img src='determinant.png'>

In [41]:
# Inverse
inverse = np.linalg.inv(A)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


<img src='inverse.png'>

<h3>Advanced Indexing</h3>

In [42]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])  # [10, 30, 50]

# Boolean indexing
print(arr[arr > 25])  # [30, 40, 50]


[10 30 50]
[30 40 50]


<h3>Reshaping and Transposing</h3>

In [33]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


# Transpose
transposed = arr.T
print(transposed)


[[1 4]
 [2 5]
 [3 6]]


In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

<img src='transpose.png'>

In [45]:
# Reshape
reshaped = arr.reshape((3, 2))
print(reshaped)


[[1 2]
 [3 4]
 [5 6]]


<h3>Advanced Broadcasting</h3>

In [35]:
arr = np.array([[1], [2], [3]])
vector = np.array([10, 20, 30])
result = arr + vector
print(result)


[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [36]:
arr1 = np.array([[1,2,7], [2,3,9], [3,4,89]])

In [37]:
arr1.shape

(3, 2)

<h3>Sorting</h3>

In [47]:
arr = np.array([3, 1, 2])
sorted_arr = np.sort(arr)
print(sorted_arr)

# Argsort (indices of sorted array)
indices = np.argsort(arr)
print(indices)


[1 2 3]
[1 2 0]


<h3>Working with Huge Data</h3>

In [48]:
# Generate a large array
large_arr = np.random.rand(1_000_000)

# Perform computations efficiently
print(np.sum(large_arr))  # Fast summation


500047.5445865694


<h3>Save and Load</h3>


In [38]:
arr=np.array([3,4,6])

In [39]:
# Save to file
np.save('array1.npy', arr)


In [40]:
# Load from file
loaded_arr = np.load('array1.npy')
print(loaded_arr)


[3 4 6]


<h3>Image Processing</h3>

In [41]:
from PIL import Image

image = Image.open('array.jpg')
image_array = np.array(image)




In [43]:
image_array.shape

(180, 341, 3)

In [44]:
image_array.size

184140

In [46]:
arr1=image_array.reshape(341,180,3)

In [47]:
print(arr1)


[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [253 253 253]
  [253 253 253]
  [253 253 253]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


In [42]:
print(image_array)

[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 ...

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]


In [48]:
# Manipulate image array
processed_image = image_array // 2
processed_image_pil = Image.fromarray(processed_image)
processed_image_pil.show()

Image Opening: The image is loaded using the PIL.Image.open() function, which returns an image object. This works well for most image formats.

Conversion to NumPy Array: When you convert the image to a NumPy array with np.array(image), it turns the image into a multi-dimensional NumPy array (height x width x channels, where channels are 3 for RGB or 4 for RGBA).

Manipulating the Image Array: You are performing an operation (image_array // 2) which divides the pixel values by 2, effectively dimming the image.

Back to Image: After manipulating the NumPy array, you use Image.fromarray(processed_image) to convert the array back to an image. Ensure that the array you use is in the correct range (0-255 for typical images) and has the correct datatype (uint8).

<h3>Real-Life Use: Investment firms use NumPy for Monte Carlo simulations, Value at Risk (VaR) calculations, and optimizing the asset allocation for maximizing returns while minimizing risk.</h3>

In [54]:
import numpy as np

# Simulate daily returns of three assets in a portfolio
np.random.seed(42)
returns = np.random.randn(1000, 3)  # 1000 days, 3 assets



In [55]:
# Compute the expected return and covariance matrix
expected_returns = np.mean(returns, axis=0)
cov_matrix = np.cov(returns.T)


In [56]:
# Portfolio weights (initial guess)
weights = np.array([0.4, 0.3, 0.3])


In [57]:
# Portfolio return and risk (standard deviation)
portfolio_return = np.sum(weights * expected_returns)
portfolio_risk = np.sqrt(np.dot(weights.T, np.dot(cov_matrix, weights)))

In [58]:

print(f"Expected Portfolio Return: {portfolio_return:.4f}")
print(f"Portfolio Risk (Standard Deviation): {portfolio_risk:.4f}")

Expected Portfolio Return: 0.0343
Portfolio Risk (Standard Deviation): 0.5649


Example: Medical Imaging (MRI Scan Processing)
MRI scans and other medical images are stored as large arrays (pixel values). NumPy helps in processing and analyzing these images, such as enhancing image quality, extracting features, and applying filters.

Real-Life Use: Doctors and medical professionals use processed images for diagnosis, for example, identifying tumors or tracking the progression of diseases like Alzheimer's.
python
Copy code


In [60]:
from PIL import Image
import numpy as np

# Load an MRI scan image (as an example)
image = Image.open('mri.jpg')

# Convert image to a NumPy array
image_array = np.array(image)

# Apply a simple threshold to detect regions of interest (e.g., tumor)
thresholded_image = (image_array > 100).astype(np.uint8) * 255

# Convert back to image and show
thresholded_image_pil = Image.fromarray(thresholded_image)
thresholded_image_pil.show()
