In [1]:
l1=[1,2.3]
l2=[2,3,4]

In [2]:
l1+l2

[1, 2.3, 2, 3, 4]

In [3]:
!pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [17]:
arr1 = np.array([1,2,3])
arr2=np.array([2,3,4])

In [9]:
arr1+arr2

array([3, 5, 7])

In [10]:
arr1.shape

(3,)

In [18]:
arr2 = np.array([[1,2,3],[2,3,4]])

In [12]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
arr1.shape

(2, 3)

In [19]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [15]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
arr3.shape

(2, 2, 2)

In [20]:
arr1.size

3

In [21]:
arr2.size

6

In [22]:
arr3.size

8

In [23]:
type(l1)

list

In [24]:
type(arr2)

numpy.ndarray

In [25]:
arr2.dtype

dtype('int32')